language: c
script: "sudo apt-get install -y g++ build-essential autoconf automake cmake doxygen bison flex libncurses5-dev libsdl1.2-dev libreadline-dev libusb-dev texinfo libgmp3-dev libmpfr-dev libelf-dev libmpc-dev libfreetype6-dev zlib1g-dev libtool libtool-bin subversion git tcl unzip wget"
script: "git clone https://github.com/pspdev/psptoolchain.git"
script: "cd psptoolchain"
script: "export PSPDEV=~/pspdev"
script: "export PATH=$PATH:$PSPDEV/bin"
script: "sudo toolchain.sh"
script: "make -f psp/MakefileNew"
